### ISSUE TITLE
git clone returned non-zero exit status 128

### ISSUE THREAD

**Issue by cryham** [gabrys/svn2github#5]
Hi, I was trying to update my fork of doublecmd, but it ends with this output:

C:\_\dc3>python svn2github.py update cryham/doublecmd-test
Cloning git@github.com:cryham/doublecmd-test.git
Traceback (most recent call last):
  File "svn2github.py", line 178, in <module>
    main()
  File "svn2github.py", line 173, in main
    sync_github_mirror(args.github_repo, args.cache_dir, new_svn_url=new_svn_url)
  File "svn2github.py", line 122, in sync_github_mirror
    git_clone(github_url, git_dir)
  File "svn2github.py", line 84, in git_clone
    run_git_cmd(["clone", git_src, "."], git_dir)
  File "svn2github.py", line 35, in run_git_cmd
    return proc.run(["git"] + args, check=True, cwd=git_dir, stderr=DEVNULL, stdin=DEVNULL, stdout=PIPE)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'clone', 'git@github.com:cryham/doublecmd-test.git', '.']' returned non-zero exit status 128.

Any hints on what went wrong? Or why git clone fails? 128 seems to mean "unexpected error".
I'm on Windows 7, I got Python 3.7, and I can clone without problems from git@github.com:cryham/doublecmd-test.git

I get the same error when trying import command (on my new empty repo dc):
C:\_\dc4>python svn2github.py import cryham/dc svn.code.sf.net/p/doublecmd/code/trunk

**Comment by cryham** [comment]
OK I updated my Git client version (it was from 2017) and  I got further, this error doesn't happen.
I'm also starting svn2github.py in MinGW (Git Bash) now.
And using for svn url: https://svn.code.sf.net/p/doublecmd/code/trunk
